### ISSUE TITLE
0.4 Progress map

### ISSUE THREAD

**Issue by lifehome** [lifehome/Fe#1]
# TODO list
- [x] Fix the debug messages implemented before.
- [ ] Reimplement the create/remove command.
- [x] Repackage Fe.
- [ ] Test out bugs.

**Comment by SimSonic** [comment]
1. Why is it needed to repackage classes?
2. Does create/remove commands really needed here? I think they can be removed completely. Keep one 'clean' subcommand, it'll be enough.

**Comment by lifehome** [comment]
Closing as repo is inactive.
